(ns propose-repo-context
  "Generate or write .llm/repo-context.edn for existing template users and
   retrofit adoption of existing Clojure/Polylith repositories.

   Default mode prints a candidate only. Writing requires :write true and is
   intended to be called by apply-repo-context-migration.sh after human approval."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.pprint :as pprint]
   [clojure.string :as str]
   [detect-repo-profile :as profile]))

(def manifest-path ".llm/repo-context.edn")
(def version-path ".llm/template-version.edn")
(def template-name "clojure-polylith-llm-starter")

(def default-ownership
  {:project-owned
   #{".llm/memory/adr/NNNN-*.md"
     ".llm/reference-repos.edn"
     "components/*/**"
     "bases/*/**"
     "projects/*/**"}

     :template-owned
     #{"CLAUDE.md"
       ".llm/guide/"
       ".llm/scripts/"
       ".clj-kondo/polyguard/"
       ".llm/template-version.edn"
       ".llm/migrations/"
       ".llm/memory/archive/maintainer-discussions/"
     ".llm/repo-context.edn"
     ".llm/memory/adr/README.md"
     ".llm/memory/adr/template.md"
     "components/README.md"
     "bases/README.md"
     "projects/README.md"}

   :template-only
   #{".llm/template-only/"}

   :section-scoped
   {".llm/memory/KNOWLEDGE.md" {:template ["§0"]      :project ["§1+"]}
    ".llm/memory/QUESTIONS.md" {:template ["§0" "§1"] :project ["§2+"]}
    "IDEA.md"                  {:template ["§0"]      :project ["§1+"]}
    "DESIGN.md"                {:template ["§0"]      :project ["§1+"]}}})

(defn- slurp-if-exists [path]
  (let [f (io/file path)]
    (when (.isFile f)
      (slurp f))))

(defn- read-manifest []
  (when-let [s (slurp-if-exists manifest-path)]
    (try
      (edn/read-string s)
      (catch Exception _ nil))))

(defn- read-template-version []
  (when-let [s (slurp-if-exists version-path)]
    (try
      (edn/read-string s)
      (catch Exception _ nil))))

(defn- ownership-source [existing]
  (if-let [ownership (:ownership existing)]
    {:ownership ownership
     :source :existing-manifest}
    {:ownership default-ownership
     :source :script-default}))

(defn- default-adoption-mode [existing requested]
  (or requested
      (when (= :project (:repo-kind existing))
        (:adoption-mode existing))
      :retrofit))

(defn candidate
  [{:keys [root project-name workspace-kind adoption-mode capabilities]}]
  (let [existing (read-manifest)
        template-version (read-template-version)
        detected (profile/detect (or root "."))
        ownership (ownership-source existing)
        caps (or capabilities
                 (:capabilities existing)
                 (:capabilities detected)
                 #{})
        caps (cond-> (set caps)
               true (conj :llm-guides))]
    {:repo-kind :project
     :derived-from (or (:template-name existing)
                       (:derived-from existing)
                       (:template-name template-version)
                       template-name)
     :project-name (or project-name (:project-name existing) (:project-name detected))
     :template-source-revision (or (:template-source-revision existing)
                                   (:source-git-revision template-version))
     :migration-schema (or (:migration-schema existing)
                           (:migration-schema template-version)
                           1)
     :applied-migrations (or (:applied-migrations existing)
                             (when-let [head (:migration-head template-version)]
                               #{head})
                             #{})
     :workspace-kind (or workspace-kind (:workspace-kind existing) (:workspace-kind detected))
     :adoption-mode (default-adoption-mode existing adoption-mode)
     :capabilities caps
     :ownership (:ownership ownership)
     :migration {:status :proposed
                 :ownership-source (:source ownership)
                 :detected detected}}))

(defn- write-manifest! [m {:keys [overwrite]}]
  (let [f (io/file manifest-path)]
    (when (and (.exists f) (not overwrite))
      (throw (ex-info "manifest exists; pass :overwrite true to replace it"
                      {:path manifest-path})))
    (.mkdirs (.getParentFile f))
    (spit f
          (str ";; .llm/repo-context.edn — リポジトリのモード/所有権 manifest（SSOT）\n"
               ";; Generated by .llm/scripts/apply-repo-context-migration.sh after human approval.\n"
               ";; Edit only after confirming repo-kind / workspace-kind / adoption-mode with the project owner.\n\n"
               (with-out-str (pprint/pprint m))))))

(defn- normalize-keywords [m ks]
  (reduce (fn [acc k]
            (if-let [v (get acc k)]
              (assoc acc k (if (keyword? v) v (keyword v)))
              acc))
          m
          ks))

(defn run [opts]
  (let [opts (-> opts
                 (normalize-keywords [:workspace-kind :adoption-mode])
                 (update :capabilities #(when % (set %))))
        m (candidate opts)]
    (if (:write opts)
      (try
        (write-manifest! (dissoc m :migration) opts)
        (println (str "wrote " manifest-path))
        (catch Exception e
          (println (str "ERROR: " (.getMessage e)))
          (System/exit 1)))
      (do
        (println ";; Proposed .llm/repo-context.edn")
        (println ";; Review with the human owner before applying.")
        (pprint/pprint m)))))
